# Generated by Django 5.1.4 on 2025-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='pending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
