# Generated by Django 5.1.4 on 2025-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='active',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
