# Generated by Django 5.1.4 on 2025-01-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_status_todo_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
